//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytics_V2.AnalyticsWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalyticsWebService.AnalyticsSoap")]
    public interface AnalyticsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Path", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_Path(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Set_Path", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Set_Path(string type, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Function_Mandatory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Function_Mandatory(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Countries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Countries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Types", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Types();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Pucs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Pucs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Requete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Requete(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_puc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_puc(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_month", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_month(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_years", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_years(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_types", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_types(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_countries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_countries(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert(string puc, string type, string pays, string data, string datamod, int timeprocess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Authenticate(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_password_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Get_password_id(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_user(string machine, int access_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_access_type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_access_type(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_access_type_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Update_access_type_id(string user_name, int access_type_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Update_User(string oldUser, string newUser, int access_type_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Users", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Users();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Delete_User(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Add_User(string user, int access_type_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnalyticsSoapChannel : Analytics_V2.AnalyticsWebService.AnalyticsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalyticsSoapClient : System.ServiceModel.ClientBase<Analytics_V2.AnalyticsWebService.AnalyticsSoap>, Analytics_V2.AnalyticsWebService.AnalyticsSoap {
        
        public AnalyticsSoapClient() {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get_Path(string type) {
            return base.Channel.Get_Path(type);
        }
        
        public bool Set_Path(string type, string path) {
            return base.Channel.Set_Path(type, path);
        }
        
        public string[] Get_Function_Mandatory(string type) {
            return base.Channel.Get_Function_Mandatory(type);
        }
        
        public string[] Get_Countries() {
            return base.Channel.Get_Countries();
        }
        
        public string[] Get_Types() {
            return base.Channel.Get_Types();
        }
        
        public string[] Get_Pucs() {
            return base.Channel.Get_Pucs();
        }
        
        public System.Data.DataSet Requete(string condition) {
            return base.Channel.Requete(condition);
        }
        
        public System.Data.DataSet Count_by_puc(string condition) {
            return base.Channel.Count_by_puc(condition);
        }
        
        public System.Data.DataSet Count_by_month(string condition) {
            return base.Channel.Count_by_month(condition);
        }
        
        public System.Data.DataSet Count_by_years(string condition) {
            return base.Channel.Count_by_years(condition);
        }
        
        public System.Data.DataSet Count_by_types(string condition) {
            return base.Channel.Count_by_types(condition);
        }
        
        public System.Data.DataSet Count_by_countries(string condition) {
            return base.Channel.Count_by_countries(condition);
        }
        
        public bool Insert(string puc, string type, string pays, string data, string datamod, int timeprocess) {
            return base.Channel.Insert(puc, type, pays, data, datamod, timeprocess);
        }
        
        public string Authenticate(string login, string password) {
            return base.Channel.Authenticate(login, password);
        }
        
        public int Get_password_id(string login, string password) {
            return base.Channel.Get_password_id(login, password);
        }
        
        public bool Insert_user(string machine, int access_type) {
            return base.Channel.Insert_user(machine, access_type);
        }
        
        public string Get_access_type(string user_name) {
            return base.Channel.Get_access_type(user_name);
        }
        
        public object Update_access_type_id(string user_name, int access_type_id) {
            return base.Channel.Update_access_type_id(user_name, access_type_id);
        }
        
        public object Update_User(string oldUser, string newUser, int access_type_id) {
            return base.Channel.Update_User(oldUser, newUser, access_type_id);
        }
        
        public System.Data.DataSet Get_Users() {
            return base.Channel.Get_Users();
        }
        
        public object Delete_User(string user) {
            return base.Channel.Delete_User(user);
        }
        
        public object Add_User(string user, int access_type_id) {
            return base.Channel.Add_User(user, access_type_id);
        }
    }
}
