//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytics_V2.Analytics_service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Analytics_service.AnalyticsSoap")]
    public interface AnalyticsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Path", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_Path(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Set_Path", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Set_Path(string type, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Function_Mandatory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Function_Mandatory(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Countries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Countries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Types", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Types();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Pucs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Pucs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Requete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Requete(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_puc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_puc(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_month", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_month(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_years", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_years(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_types", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_types(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count_by_countries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Count_by_countries(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert(string puc, string type, string pays, string data, string datamod, int timeprocess);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnalyticsSoapChannel : Analytics_V2.Analytics_service.AnalyticsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalyticsSoapClient : System.ServiceModel.ClientBase<Analytics_V2.Analytics_service.AnalyticsSoap>, Analytics_V2.Analytics_service.AnalyticsSoap {
        
        public AnalyticsSoapClient() {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalyticsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get_Path(string type) {
            return base.Channel.Get_Path(type);
        }
        
        public bool Set_Path(string type, string path) {
            return base.Channel.Set_Path(type, path);
        }
        
        public string[] Get_Function_Mandatory(string type) {
            return base.Channel.Get_Function_Mandatory(type);
        }
        
        public string[] Get_Countries() {
            return base.Channel.Get_Countries();
        }
        
        public string[] Get_Types() {
            return base.Channel.Get_Types();
        }
        
        public string[] Get_Pucs() {
            return base.Channel.Get_Pucs();
        }
        
        public System.Data.DataSet Requete(string condition) {
            return base.Channel.Requete(condition);
        }
        
        public System.Data.DataSet Count_by_puc(string condition) {
            return base.Channel.Count_by_puc(condition);
        }
        
        public System.Data.DataSet Count_by_month(string condition) {
            return base.Channel.Count_by_month(condition);
        }
        
        public System.Data.DataSet Count_by_years(string condition) {
            return base.Channel.Count_by_years(condition);
        }
        
        public System.Data.DataSet Count_by_types(string condition) {
            return base.Channel.Count_by_types(condition);
        }
        
        public System.Data.DataSet Count_by_countries(string condition) {
            return base.Channel.Count_by_countries(condition);
        }
        
        public bool Insert(string puc, string type, string pays, string data, string datamod, int timeprocess) {
            return base.Channel.Insert(puc, type, pays, data, datamod, timeprocess);
        }
    }
}
